#!/bin/bash
# ПРАВИЛЬНЫЕ КОМАНДЫ CURL ДЛЯ ТЕСТИРОВАНИЯ

echo "🔥 ПРАВИЛЬНЫЕ КОМАНДЫ ДЛЯ ТЕСТИРОВАНИЯ АТАК"
echo "=========================================="
echo ""
echo "🎯 Отправляйте эти команды в НОВОМ терминале:"
echo ""
echo "1. Нормальный запрос:"
echo "   curl -s \"http://localhost:3001/\""
echo ""
echo "2. SQL Injection:"
echo "   curl -G -s \"http://localhost:3001/rest/products/search\" --data-urlencode \"q=' OR '1'='1\""
echo ""
echo "3. XSS:"
echo "   curl -G -s \"http://localhost:3001/rest/products/search\" --data-urlencode \"q=<script>alert('XSS')</script>\""
echo ""
echo "4. Path Traversal:"
echo "   curl -s \"http://localhost:3001/assets/../../../etc/passwd\""
echo ""
echo "5. Command Injection:"
echo "   curl -G -s \"http://localhost:3001/rest/products/search\" --data-urlencode \"q='; ls -la /\""
echo ""
echo "6. Еще SQL Injection:"
echo "   curl -G -s \"http://localhost:3001/rest/products/search\" --data-urlencode \"q=' UNION SELECT * FROM users--\""
echo ""
echo "📊 После каждой команды смотрите обнаружения в окне монитора!"
echo ""
echo "💡 Используйте -s для тихого режима, без него увидите HTML ответ"
